name: Element Roast Co
favicon: null
layout_spectrum: 0.1818492915481329
typography_spectrum: 0.7677407192531973
title: Element Roasting Co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f0f5f9'
    - '#010101'
    - '#aa8563'
    - '#684a2f'
    - '#bac1c7'
  brandStrength: 0.75
  lightness: 0.0625
  saturation: 0.0625
  rhythmicContrast: 0.36986127542331815
purpose: []
