name: Element Roast Co
favicon: null
layout_spectrum: 0.1818492915481329
typography_spectrum: 0.7677407192531973
title: Element Roasting Co
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#98b8dc'
    - '#646867'
    - '#7e8e84'
    - '#131d1c'
    - '#e1eace'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
